// https://leetcode.com/problems/find-the-difference/description/
/*
 You are given two strings s and t.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Return the letter that was added to t.

 Example 1:
 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.
 Example 2:

 Input: s = "", t = "y"
 Output: "y"
 */

func findTheDifference(_ s: String, _ t: String) -> Character {
    var mapS:[Character: Int] = [:]
    for char in s {
        mapS[char, default: 0] += 1
    }
    // Decrement with t; the first mismatch is the answer
    for char in t {
        let count = mapS[char, default: 0]
        if count == 0 {
            return char
        }
        mapS[char] = count - 1
    }
    // Should never reach here for valid input
    return " "
}
